/**
 * WireGuard config rendering — private keys injected only at write-to-data-dir time.
 * Endpoint uses hostname foundation (DDNS) — not hardcoded public IP in source.
 */

import type { DeviceRegistry } from './deviceRegistry.js';
import {
  VS_WG_SUBNET,
  VS_WG_SERVER_IP,
  VS_WG_SERVER_INFRA,
} from './networkConstants.js';

export function renderServerWgConf(input: {
  privateKeyPlaceholder?: string;
  listenPort: number;
  peers: Array<{ public_key: string; private_ip: string; device_id: string }>;
}): string {
  const lines = [
    '# VS SERVER WireGuard — generated; private key from data store only',
    '[Interface]',
    `Address = ${VS_WG_SERVER_IP}/24`,
    `# Infrastructure ${VS_WG_SERVER_INFRA}; full VS private ${VS_WG_SUBNET}`,
    `ListenPort = ${input.listenPort}`,
    `PrivateKey = ${input.privateKeyPlaceholder || '<SERVER_PRIVATE_KEY>'}`,
    '',
  ];
  for (const p of input.peers) {
    lines.push(`# peer ${p.device_id}`);
    lines.push('[Peer]');
    lines.push(`PublicKey = ${p.public_key}`);
    lines.push(`AllowedIPs = ${p.private_ip}/32`);
    lines.push('');
  }
  return lines.join('\n');
}

export function renderPeerWgConf(input: {
  devicePrivateKeyPlaceholder: string;
  devicePrivateIp: string;
  serverPublicKey: string;
  /** hostname:WG_PORT — DDNS foundation */
  serverEndpoint: string;
  persistentKeepalive?: number;
}): string {
  return [
    '# VS peer config — private key never committed to git',
    '# Generated by VS Network Authority — do not hand-edit in product UX',
    '[Interface]',
    `Address = ${input.devicePrivateIp}/32`,
    `PrivateKey = ${input.devicePrivateKeyPlaceholder}`,
    '',
    '[Peer]',
    `PublicKey = ${input.serverPublicKey}`,
    `Endpoint = ${input.serverEndpoint}`,
    `AllowedIPs = ${VS_WG_SUBNET}`,
    `PersistentKeepalive = ${input.persistentKeepalive ?? 25}`,
    '',
  ].join('\n');
}

export function buildServerConfFromRegistry(
  registry: DeviceRegistry,
  serverPrivateKeyPlaceholder = '<SERVER_PRIVATE_KEY>'
): string {
  const meta = registry.getMeta();
  return renderServerWgConf({
    privateKeyPlaceholder: serverPrivateKeyPlaceholder,
    listenPort: meta.wg_listen_port,
    peers: registry.activePeers(),
  });
}

/** WireGuard peer endpoint string from hostname foundation. */
export function serverWgEndpoint(hostname: string | null | undefined, listenPort: number): string {
  const host = hostname && hostname.trim() ? hostname.trim() : 'VS-CORE-01';
  return `${host}:${listenPort}`;
}
